### ISSUE TITLE
Suggestion - extra indirection level to support stream IO instead of just filenames

### ISSUE THREAD

**Issue by edgargoncalves** [mjul/docjure#1]
This will be useful for webapps, at least. I currently have the following defined to support this:

	(defn load-workbook-from-stream
	  "Load an Excel .xls or .xlsx workbook from a stream."
	  [in-stream]
	  (with-open [stream in-stream]
	    (WorkbookFactory/create stream)))

	(defn stream-workbook! 
	  "Write the workbook into a stream."
	  [#^Workbook workbook]
	  (assert-type workbook Workbook)
	  (with-open [out-stream (ByteArrayOutputStream.)]
	    (.write workbook out-stream)
	    (ByteArrayInputStream. (.toByteArray out-stream))))

**Comment by mjul** [comment]
Thanks for your feedback. I am pleased to report that Docjure supports streams as of version 1.9.0.
