### ISSUE TITLE
New release needed to support auto-size-all-columns! documented in README.md

### ISSUE THREAD

**Issue by stiancor** [mjul/docjure#106]
Hi, thanks for the great work.

Just wanted to make you aware that the documentation indicates that `auto-size-all-columns!` and other new functions are available, however there is currently no release where these functions are available. It seems that the latest release 1.18.0 is from 19. of August, but these functions were added and documented on the 27. of September. Any chance you could create a new release?

thanks

**Comment by mjul** [comment]
Ok. 
If you want it right now use the snapshot build on Clojars. See project.clj for the exact name.
