### ISSUE TITLE
Web Development 

### ISSUE THREAD

**Issue by Quasaur** [mjul/docjure#30]
What you're doing here is fantastic! Are there any issues with creating | editing spreadsheets on the web? I'm converting my History of the World website (history.clmitchell.net) to a clojure/hoplon-based web app and would LOVE to use an Excel spreadsheet as my database from which to display data on the web page!

**Comment by mjul** [comment]
Glad you like it, the library works great in web applications, too. If you plan to use a spreadsheet file as a database, just make sure you get your concurrency right as it does not offer the kind of transaction control you would get with a database engine.
