### ISSUE TITLE
unable to read cells with formula referring to string value

### ISSUE THREAD

**Issue by mathiasdw** [mjul/docjure#34]
The code for read-cell first checks the date format, but during that check, POI throws because it's assuming already a numeric cell type.
It's probably rather a POI bug, but I was wondering why the date check is needed in the first place.

**Comment by mjul** [comment]
Thanks for identifying this. I was not aware of it and from you description it seems like it is a bug indeed. 
If you would investigate it a bit more and submit pull request with a test-case and a fix I would be happy to include your contribution.
Thanks for taking the time to helping improve the project. Many people rely on it for their software, so you effort will be widely appreciated.
All the best,
Martin

**Comment by mathiasdw** [comment]
Hi,
it turns out that @oholworthy  already fixed it a month ago. 
Thanks Oliver and all for the nice lib!
Closing the bug report...

**Comment by mjul** [comment]
Excellent, thank you for investigating the issue.
