### ISSUE TITLE
Generate workbook as a stream?

### ISSUE THREAD

**Issue by donbonifacio** [mjul/docjure#39]
Hello,

Any tips on how to generate the workbook as a stream? From the code I see that we can deliver the complete workbook to a stream, but I'd like to have a stream of input rows and a stream of output workbook.

**Comment by mjul** [comment]
As far as I understand, the Office Excel output format is essentially a zip compressed directory of XML files. Thus, while we could stream the input rows into the application, I think it is less likely that we could stream the document into a zip compressed directory structure.
However, Clojure uses the Apache POI library as a back-end, so it would be interesting if you could have a look at its possibilities and give a definite answer to your question.
Cheers,
Martin
