### ISSUE TITLE
create a workbook with multiple sheets

### ISSUE THREAD

**Issue by dpetranek** [mjul/docjure#48]
I'd like to be able to create a workbook with multiple sheets. I was able to get this working by re-writing the `create-workbook` function, would you be open to a pull request for this?

**Comment by russellwhitaker** [comment]
@dpetranek you should probably just go ahead and open a PR. Looks like they have 4 still open, not sure how actively maintained this is now. If you get no response after a while, you might consider forking the project yourself and publishing an updated artifact to Clojars.

**Comment by dpetranek** [comment]
I've submitted a pull request with the code that works for me. Any comments or contributions are welcome.

**Comment by mjul** [comment]
Thanks a lot for your contribution - it is a very nice feature. I am on currently vacation - I will look at the details when I get back to a computer.
Thanks
Martin

--

Martin Jul
+45 21 63 34 72
+34 635 296 277

martin@mjul.com<mailto:martin@mjul.com>



On 12. maj 2016, at 23.22, Daniel Petranek <notifications@github.com<mailto:notifications@github.com>> wrote:


I've submitted a pull request with the code that works for me. Any comments or contributions are welcome.

**Comment by mjul** [comment]
Hi Russell

It's feature complete for my own uses so the update cycle is relaxed, but I am happy to accept contributions and assign more contributors if anyone is interested in helping develop the library.

Cheers,
Martin


--

Martin Jul
+45 21 63 34 72
+34 635 296 277

martin@mjul.com<mailto:martin@mjul.com>



On 12. maj 2016, at 20.03, Russell Whitaker <notifications@github.com<mailto:notifications@github.com>> wrote:


@dpetranek<https://github.com/dpetranek> you should probably just go ahead and open a PR. Looks like they have 4 still open, not sure how actively maintained this is now. If you get no response after a while, you might consider forking the project yourself and publishing an updated artifact to Clojars.
