### ISSUE TITLE
Can we select columns by custom column name ? 

### ISSUE THREAD

**Issue by rhacker** [mjul/docjure#52]
Thanks for great library. I tried `select-column` with custom name in excel but it doesn't seem to work. Is there anyway to make it work ? I'm happy to contribute, I need some direction since I'm not familiar with the java lib.

**Comment by mjul** [comment]
Thanks for getting in touch. It would be great if you could help extend the library.

`select-columns` uses the standard Excel column names `:A`, `:B`, `:C` _etc._ 

The `select-name` function provides support for named ranges. Maybe you could use that as inspiration for updating select-columns (possibly extending it to a multi-method if necessary).

The documentation for named ranges in the POI library is here: 
http://poi.apache.org/spreadsheet/quick-guide.html#NamedRanges

**Comment by rhacker** [comment]
@mjul sorry for late update. I just found out that my file `xlsx` was read as `EXCEL97`, I'm not sure if it's a cause or not. I will investigate on this further, for now `select-columns` works just fine. Thanks for helping.
