### ISSUE TITLE
XSSF specific features

### ISSUE THREAD

**Issue by ibarrick** [mjul/docjure#66]
I needed to support hex code colors instead of the existing colors in IndexedColors, but in order to get that to work in clojure I had to change the type hints of the create-cell-style! function to be XSSFWorkbook because for some reason clojure wasn't finding the method of XSSFCellStyle that accepted XSSFColor as an argument even though I had verified that the classes (and poi version) were correct.

Is it important to you that you support HSSF? or should I submit a PR with my changes?

**Comment by mjul** [comment]
Thanks for the offer. I know some users are using the old .xls formats, so I think they would be sad to see it break if that is what you are alluding to.

**Comment by ibarrick** [comment]
Makes perfect sense. I ultimately ended up making several more breaking changes to get to where I needed to be so I think I'll just maintain my fork separately. Thanks for getting back to me!

**Comment by mjul** [comment]
I just noticed we passed the 10-year anniversary for the "new", XML-based Office data formats, so perhaps it would be reasonable to retire .xls support in a v2 of the library (simplifying the work to create a more functional API).
