### ISSUE TITLE
Very large files - Laziness ? 

### ISSUE THREAD

**Issue by amitvshah25** [mjul/docjure#72]
This is more of a question, rather than issue. I tried to read around the documents, but couldn't find much, and I am not that familiar with Apache POI .. For very large files, do we get a lazy sequence, or is the entire result-set stored in memory ? 

I have used the csv libraries of clojure, and they all return lazy sequence, so I had to be careful about holding on to the file-reader until the sequence was consumed. Not sure what is the situation with this library.

**Comment by mjul** [comment]
Normally POI and Docjure operate in-memory.
However, for larger data sets Docjure provides the option to use a (very limited) streaming API to reduce memory footprint.
