### ISSUE TITLE
way to merge cells ?

### ISSUE THREAD

**Issue by gudesh** [mjul/docjure#77]
Hi,

I'm new to the docjure lib and I need to apply a specific format over cells in a spreadsheet that I write.

In particular, I need to merge some cells like [here (StackOverflow)](https://stackoverflow.com/questions/18716032/merging-cells-in-excel-using-apache-poi) 
or at least let the contents on the first cell overflow into the next ones...

Is there a feature for this that I missed, or an example of interop with POI that I could
use ?

Thanks,

Gudesh

**Comment by mjul** [comment]
It has not been implemented, but you are welcome to do so and submit a pull request.
Thanks, Martin
